spring:
  datasource:
    url: jdbc:postgresql://scpi-inv-db:5432/scpi_inv_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

minio:
  url: "http://minio-service.minio.svc.cluster.local:9000"
  access-key: admin
  secret-key: admin-admin